### ISSUE TITLE
From react-redux-universal-hot-example to universal-redux

### ISSUE THREAD

**Issue by oyeanuj** [bdefore/redux-universal-renderer#15]
@bdefore I have been following your work on universal-redux and it looks great. I am glad this exists now.

I am wondering your thoughts or philosophy on how someone who is already underway on their project using react-redux-universal-hot-example boilerplate should think about the `universal-redux` package? Migrate or watch both? 

In general, do you plan to merge back from changes in that react-redux-universal-hot-example repository.

**Comment by bdefore** [comment]
@oyeanuj thanks, glad to hear you're thinking about using universal-redux!

first, as for bringing changes into react-redux-universal-hot-example, i'm hoping that the collaborators on that repo see the value, and i have a series of PR's open:
- to bring in universal-redux 0.x (babel5, redux-router): https://github.com/erikras/react-redux-universal-hot-example/pull/626
- to bring in universal-redux 1.x (babel5, redux-simple-router): https://github.com/erikras/react-redux-universal-hot-example/pull/685
- to bring in universal-redux 2.x (babel6, redux-simple-router): https://github.com/erikras/react-redux-universal-hot-example/pull/730

there's a lot of change there, and @quicksnap has mentioned that he's going to explore it in a test project first. here's his comments on it: https://github.com/erikras/react-redux-universal-hot-example/pull/685#issuecomment-165268798

as for migrating your own app, it may or may not be complicated, depending on how much you've modified some parts of the original repo.

places that i can think of that need would need some consideration:
- ApiClient.js. This would have to be added as a Redux middleware since it's not a part of universal-redux. You can see how I did this with a slightly modified version of ApiClient (which I call 'fetcher) in the JWT example project here: https://github.com/bdefore/universal-redux/tree/master/examples/jwt/src/redux/middleware. I don't think it should be difficult for you.
- The api server: This is also not a part of universal-redux, but should run fine independently, as long as you add the related proxy to the Express instance. My universal-redux start_es6.js does this in the PR: https://github.com/bdefore/react-redux-universal-hot-example/blob/babel6/bin/start_es6.js

other than that, everything in your `src/containers` directory should stay where they are. you'll just need to create a `config` directory with a universal-redux.config.js as mentioned in the README.

you may find it easier to start with the branch of my PR (https://github.com/erikras/react-redux-universal-hot-example/pull/730) and then drop your app into it. this assumes you'd want to update to babel 6 and redux-simple-router.

i'd definitely like to hear if you plan to do this, and would be happy to help.

**Comment by quicksnap** [comment]
If you do try to migrate your app, I'm very interested in your experience as well. As mentioned, I'm going to try and test this out on another greenfield project, however it's been taking me a while to get to it.

I haven't heard a ton of feedback from anyone using it, but I would really love to hear how it's gone for others.

**Comment by oyeanuj** [comment]
@bdefore @quicksnap I took another look at it, and I think it does make it easier to understand a lot of the data-fetching logic and the setup.

I would like to give it a shot, maybe once my project stabilizes a little bit. Hopefully, someone else can do it sooner and provide feedback. @bdefore, once it merges, would you expect people to send PRs to this library or just to the RRUHE and you would merge things back to this library?

As an aside, @bdefore, your comment above would be a really useful migration guide for that PR :)

**Comment by bdefore** [comment]
@oyeanuj i don't know that this will be merged to RRUHE, but whether or not it is a migration guide would definitely help. i'll elaborate further on the comment above and put it into a markdown doc in the repo.

**Comment by bdefore** [comment]
Let's continue this on #26
