### ISSUE TITLE
Where fetchAllData function is calling from?

### ISSUE THREAD

**Issue by pavelkornev** [bdefore/redux-universal-renderer#40]
Could not find any calls of fetchAllData function on master branch, but i found this on babel6 branch - https://github.com/bdefore/universal-redux/blob/babel6/src/server.js#L104-L127 - will it be merged into master?

**Comment by bdefore** [comment]
@pavelkornev there is an issue #16 that required it being removed, but i hope to get this back into 2.x when that is resolved. react-fetcher or something like it will probably come along in 3.x (and possibly 2.x). what all of this indicates is that a project level ability to pass a kind of middleware to the serverside render loop is in order, where you could provide fetchAllData handler. i'd welcome ideas on how to accomplish that.

**Comment by bdefore** [comment]
Also see #43

**Comment by bdefore** [comment]
@pavelkornev I've added support for async-props library with release 3.0.0-rc5. That should provide similar functionality to what you get with `fetchAllData`. Usage is here: https://github.com/rackt/async-props#usage (you'll only need to care about the part about adding a static `loadProps` function, the rest is handled for you in universal-redux)

**Comment by arkist** [comment]
@bdefore now it has the same issue as me.: https://github.com/rackt/async-props/issues/30
Have any idea?

**Comment by bdefore** [comment]
@arkist the warning you're seeing is probably not worth concerning about. it's normal on development due to the HMR server, and in production, even if a clientside render is a different checksum, because of React's virtual DOM diffing, it may not amount to a significant performance impact. to diagnose whether it is or not, what i recommend is to disable JavaScript and reload the page. note that in universal-redux styles currently do not load with JS disabled in development (#37)

**Comment by arkist** [comment]
@bdefore sure, not in production. thanks for explain. 
now I feel more comfortable ;)

**Comment by sars** [comment]
got the same warning...

**Comment by sars** [comment]
@arkist @bdefore https://github.com/bdefore/universal-redux/pull/46 should fix problem

**Comment by arkist** [comment]
@sars thanks!
