### ISSUE TITLE
Source maps show transpiled code 

### ISSUE THREAD

**Issue by aam229** [bdefore/redux-universal-renderer#49]
On Windows (I haven't tried it on Linux), running the starter project with `npm run dev` generates source maps but they are for the transpiled (es5) code. If I build it with `npm run build`, I get the source maps for the original es6/JSX code. Updating [this line](https://github.com/bdefore/universal-redux/blob/e9827ce0c9ef244520129e57adbb82173d2ad1de/bin/merge-babel-config.js#L35) to

``` js
const jsLoaders = isProduction ? [babelLoader, strip.loader('debug')] : [babelLoader];
```

seems to fix it. I'm not familiar enough with Babel loaders to explain why it works one way and not the other, it's only based on my observations. You will probably want to test it out more thoroughly than I did. 

The second issue is that the `strip-loader` is used when the environment is set to development. I believe [this line](https://github.com/bdefore/universal-redux/blob/e9827ce0c9ef244520129e57adbb82173d2ad1de/bin/merge-babel-config.js#L5), should be changed to

``` js
const isProduction = process.env.NODE_ENV === 'production';
```

Please let me know if I can help you with this issue (or any other).

**Comment by bdefore** [comment]
@aam229 oof, that second one is embarassing. thanks for catching that. strip-loader has come along for the ride from the upstream project, and in fact as configured was not stripping anything since no parameters were being provided. i've removed it from UR with 3.0.0-rc10. in case anyone else wants to use it, you should be able to do so by providing a custom webpack configuration specifying it as your js loader.

**Comment by bdefore** [comment]
actually I misread the docs for it, it was actually stripping `debug` calls. but ideally this should be configurable to the project, so i'll need to look into how to expose that better.

**Comment by aam229** [comment]
Thank you for fixing (and releasing) it so quickly.
