### ISSUE TITLE
Double serialization in config?

### ISSUE THREAD

**Issue by jazzido** [bdefore/redux-universal-renderer#67]
My `universal-redux-config.js` declares this global:

``` javascript
globals: {
  //...
  __API_ENDPOINT__: process.env.API_ENDPOINT || 'http://localhost:9292'
  // ...
}
```

My server sees `__API_ENDPOINT__` as `"http://localhost:9292/"` (quotes included). Looks like there's a double serialization somewhere in the config code.

**Comment by bdefore** [comment]
@jazzido a while back, i made a change to stringify all incoming globals here https://github.com/bdefore/universal-redux/blob/master/bin/merge-configs.js#L83. i believe the issue was that if they weren't at all, the server would fail to start when given certain values. for now, you can get around it by using `JSON.parse` on the other end what should already be strings. Not ideal I agree.

**Comment by jazzido** [comment]
Submitted PR #72, there was a double serialization in `configure.js`.
