### ISSUE TITLE
Question: styles and best practice

### ISSUE THREAD

**Issue by bapti** [bdefore/redux-universal-renderer#73]
Hi,

Firstly - great work on the repository, I far prefer pulling in a library with some well defined APIs than starting from a skeleton.  

Secondly I was wondering if you've got time I could use some advice on how to handle styles with your library.  Here's an example of some of my JSX from my project.

``` js
import theme from './../../theme/imports.less'

<div className={theme.Navbar}>
<a className={theme['Navbar-logo'] + ' ' + theme['u-inlineBlock'] + ' ' + theme['u-alignMiddle']}  href="/">
```

In order to get the styles to apply to my components I find I'm doing a lot of stuff like this.  I could get rid of the dashes to make life easier for myself but that's putting the designer out and making them rewrite a lot of their files and change their naming conventions.

I watched the video from react europe on styles from (Michael Chan)[https://www.youtube.com/watch?v=ERB1TJBn32c] and that seems like pretty sensible advice of having a base theme and then using inline styles for anything relating to state.
#### Questions

The styles all get renamed and given hashes so it looks like this - why does it do this?  Is it something to do with cache invalidation? Is it possible to make it not do this?  For the utility classes should I be wrapping components in other components to apply the styles rather than applying multiple classes to the same element?

``` css
.Navbar___1ZjlJ {
 ...
}
.Navbar-logo___10FwY {
  ...
}
```

Thanks for any help and advice
Neil

**Comment by bapti** [comment]
To add to this. I've dug around a bit and found the docs in webpack for [local identies](https://github.com/webpack/css-loader#local-scope) in the css loader.  This makes sense for specific components so you don't have to do manual name spacing but not for the over-arching theme?

**Comment by bdefore** [comment]
@bapti there's currently lots of opinions in the style space. universal-redux is configured by default for styling using CSS Modules, and as you've discovered the hash suffix is applied in order to enforce locally scoped styles, which brings a number of benefits. this shouldn't affect you other than the additional visual noise while digging through the chrome inspector.

in general there's a lot of overlap in concern between between CSS Modules and say BEM (which is IMO a rather ugly namespacing/metaprogramming layer over a language that doesn't provide enough tools to do the job on its own). BEM and its cousins imply significance with a certain number underscores and hyphens. CSS Modules is stricter, leveraging Webpack to be scoped explicitly where they should be. unfortunately, this shared concern means some strain working with existing styling codebases that are used to sharing a lot of style across the global scope.

syntactically, your particular case of having to add styles with i.e. `className={theme['Navbar-logo'] + ' ' + theme['u-inlineBlock'] + ' ' + theme['u-alignMiddle']}` looks rather painful. i use this library to alleviate some of that issue: https://github.com/gajus/react-css-modules

there is an issue for allowing broader control over Webpack configuration, including overriding style choices #66 i'd like to know as many use cases as possible to see if there's another way other than supporting overwriting UR defaults.

**Comment by bapti** [comment]
@bdefore that's great thanks for your help.  We've got for pre compiling the overarching theme for controlling layout and then having component specific stuff in a less file that sits alongside the component.  If you need any help with documentation I'd be happy to do some.
