### ISSUE TITLE
how running on production?

### ISSUE THREAD

**Issue by sexyoung** [bdefore/redux-universal-renderer#74]
sorry I have a stupid question... :disappointed: 

I finish my website use universal-redux.
if on my Mac, how to simulation production environment?
now I already `npm run build`,
and I don't know what is next step I should to do....
my env: 
- node 5.1
- nginx 1.8.0

Thanks universal-redux Team! :+1:

**Comment by bdefore** [comment]
@sexyoung you could add the following to your package.json scripts: `"server": "NODE_ENV=production NODE_PATH=./src universal-redux-server",` and run `npm run server' locally to simulate production. i added this to the starter repo.

**Comment by sexyoung** [comment]
Thank you @bdefore , you've been such a great help. :sunny:

**Comment by bdefore** [comment]
happy to help :+1:

**Comment by pavelkornev** [comment]
@bdefore why all babel dependencies are in production dependencies section in package.json?

**Comment by bdefore** [comment]
@pavelkornev as i understand npm3 behavior, if universal-redux listed its dependencies in devDependencies, they would not be installed if universal-redux itself was a dependency of your project. this would mean each project would need to explicitly include webpack, loaders, et. al. in order to work with UR.
