### ISSUE TITLE
Server-side React render was discarded

### ISSUE THREAD

**Issue by nathanielks** [bdefore/redux-universal-renderer#92]
Happy Thursday!

First off, thank you _so_ much for this project. I was thinking just yesterday how I wish someone would separate the webpack configuration into a module because it really should be separate from the rest of the app. Lo and behold, I discover this today!

I've cloned the latest copy of https://github.com/bdefore/universal-redux-starter, updated `universal-redux` to 3.0.2, ran `npm run dev`, loaded `http://localhost:3000`, and am greeted with

```
WARNING: Server-side React render was discarded. Make sure that your initial render does not contain any client-side code.
```

I saw your comment over [here](https://github.com/bdefore/universal-redux/issues/33#issuecomment-171764262) and wanted to let you know it's still present in 3.x!

**Comment by nathanielks** [comment]
How can I be of service?

**Comment by bdefore** [comment]
@nathanielks This is a regression from some previous builds due to how the dev tools are initialized, and a bit of a false alarm because devtools are not relevant for production. However, it does obscure legitimate discrepancies. Something along these lines may fix the issue: https://github.com/erikras/react-redux-universal-hot-example/pull/961 and I'll look into it in the future, though if you'd like to supply a fix I'd be much obliged!

**Comment by jazzido** [comment]
Hi @nathanielks: Did the update to `react-router-redux 4.0.0` solved this issue? I noticed a possible related bug: #91 — Thanks!

**Comment by nathanielks** [comment]
@jazzido haha, unfortunately I gave up on it as I was experiencing different issues unrelated to this one!

**Comment by goldensunliu** [comment]
👍 as long as it works in prod I am okay with it for now
